#!/bin/sh

case "$1" in

	""|start|restart|stop)
		exit 0
		;;

	info)
        echo "Info: <b>CUxD-Highcharts</b>"
        echo "Info: <br>Aufruf: <a href="/addons/cuxchart/" target="_blank">http://CCU/addons/cuxchart</a>"
        echo "Info: <br>Readme: <a href="https://raw.github.com/hobbyquaker/CUxD-Highcharts/master/README.md" target="_blank">Lies mich!</a>"
        echo "Name: CUxD-Highcharts"
        echo "Version: 1.3.5"
        echo "Operations: uninstall"
        ;;
	uninstall)
		rm -r /usr/local/etc/config/addons/cuxchart
		;;
	*)
        echo "Usage: cuxd-highcharts {info|uninstall}" >&2
        exit 1
        ;;

esac

exit 0
