#!/bin/sh
case "$1" in
	""|start|restart|stop)
		;;
	info)
		VERSION=`sed -rn 's/^.*version:"([^"]+)/\1 /p' /usr/local/etc/config/addons/www/cuxchart/js/cuxchart.*js | awk '{ print $1 }'`
		echo "Info: <b>CUxD-Highcharts</b>"
		echo "Info: <br>Menu: <a href="/addons/cuxchart/menu.html" target="_blank">/addons/cuxchart/menu.html</a>"
		echo "Info: <br>Readme: <a href="https://raw.githubusercontent.com/hobbyquaker/CUxD-Highcharts/master/README.md" target="_blank">Lies mich!</a>"
		echo "Name: CUxD-Highcharts"
		echo "Version: $VERSION"
		echo "Operations: uninstall"
		;;
	uninstall)
		rm -rf /usr/local/etc/config/addons/www/cuxchart/
		;;
	*)
		echo "Usage: cuxd-highcharts {info|uninstall}" >&2
		exit 1
		;;
esac
exit 0
