#!/bin/sh

WWW_DIR=/usr/local/etc/config/addons/www/
RC_DIR=/usr/local/etc/config/rc.d

mount /usr/local 2>/dev/null

# Programme kopieren
cp -pR cuxchart $WWW_DIR/

# Startscript kopieren
cp -p cuxd-highcharts $RC_DIR/cuxchart

sync
